### ISSUE TITLE
Adding automatic formatter to development pipeline

### ISSUE THREAD

**Issue by tatuhtuni** [Project-C-SQL/postgresql-for-novices#52]
To be discussed in sprint planning

**Comment by j-nikki** [comment]
Formatter options reside in workspace settings file (tentative version):
```json
{
    "python.analysis.typeCheckingMode": "strict",
    "python.testing.pytestArgs": [
        "src"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "editor.formatOnSave": true,
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "--line-length=80"
    ],
    "isort.args": [
        "--profile",
        "black"
    ],
    "python.linting.mypyEnabled": true,
    "python.linting.mypyArgs": [
        "--follow-imports=silent",
        "--ignore-missing-imports",
        "--show-column-numbers",
        "--no-pretty"
    ],
    "python.linting.pylintEnabled": true,
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
}
```

But this occupies whole of the workspace settings file - what if developer needs local overrides?
Discussed here: https://github.com/Microsoft/vscode/issues/37519

> Closing this in favour of using new Workspace as a solution.

=> Look into workspace settings.

So the task is:
1. Coming up with formatter configuration that matches CI/CD pipeline's
2. Coming up with an unintrusive way to version control the configuration

**Comment by j-nikki** [comment]
Need an editor-agnostic solution, independent of VS Code.
E.g., git hook? Shell script that can be invoked by editor of choice?

**Comment by j-nikki** [comment]
https://towardsdatascience.com/python-code-formatting-made-simple-with-git-pre-commit-hooks-9233268cdf64
