### ISSUE TITLE
Fix QEPParser crashes on sql syntax errors

### ISSUE THREAD

**Issue by throwaway-3** [Project-C-SQL/postgresql-for-novices#91]
QEPParser executes sql queries prefixed with `EXPLAIN ANALYZE` using the psycopg library.
The program crashes when psycopg detects sql error and throws an exception that is not caught in QEPParser.

Exploration / partial fix in branch tmp/qepparser-crash

**Comment by tatuhtuni** [comment]
Moved to Sprint backlog from Ready, because there is no work verifiably done on this.
